project(compute_particles_c-${POSTFIX})

foreach(MODE ${WISDOM_EXAMPLES_MODES})
  if(MODE STREQUAL "headers")
    continue()
  elseif(MODE STREQUAL "static")
    set(TARGET ${PROJECT_NAME})
  else()
    set(TARGET ${PROJECT_NAME}-${MODE})
  endif()

  add_executable(${TARGET} entry_main.c)
  target_link_libraries(${TARGET} PRIVATE example_backend_c-${POSTFIX}-${MODE})
  wis_setup_example(${TARGET} ${MODE})
endforeach()
