#pragma once
#include <tinyxml2.h>
#include <array>
#include <filesystem>
#include <fstream>
#include <optional>
#include <span>
#include <string_view>
#include <unordered_map>
#include <vector>
#include <format>
