var annotated_dup =
[
    [ "wis", "d1/d34/namespacewis.html", [
      [ "AcceleratedGeometryInput", "d7/d87/structwis_1_1AcceleratedGeometryInput.html", "d7/d87/structwis_1_1AcceleratedGeometryInput" ],
      [ "AdapterDesc", "d3/d9f/structwis_1_1AdapterDesc.html", "d3/d9f/structwis_1_1AdapterDesc" ],
      [ "AllocationInfo", "dc/dce/structwis_1_1AllocationInfo.html", "dc/dce/structwis_1_1AllocationInfo" ],
      [ "ASAllocationInfo", "de/d1e/structwis_1_1ASAllocationInfo.html", "de/d1e/structwis_1_1ASAllocationInfo" ],
      [ "BlendAttachmentDesc", "d0/d08/structwis_1_1BlendAttachmentDesc.html", "d0/d08/structwis_1_1BlendAttachmentDesc" ],
      [ "BlendStateDesc", "dd/d2e/structwis_1_1BlendStateDesc.html", "dd/d2e/structwis_1_1BlendStateDesc" ],
      [ "BufferBarrier", "d1/dca/structwis_1_1BufferBarrier.html", "d1/dca/structwis_1_1BufferBarrier" ],
      [ "BufferRegion", "da/d8d/structwis_1_1BufferRegion.html", "da/d8d/structwis_1_1BufferRegion" ],
      [ "BufferTextureCopyRegion", "dc/d8d/structwis_1_1BufferTextureCopyRegion.html", "dc/d8d/structwis_1_1BufferTextureCopyRegion" ],
      [ "ComponentMapping", "da/d32/structwis_1_1ComponentMapping.html", "da/d32/structwis_1_1ComponentMapping" ],
      [ "DepthStencilDesc", "d2/d0b/structwis_1_1DepthStencilDesc.html", "d2/d0b/structwis_1_1DepthStencilDesc" ],
      [ "DescriptorBindingDesc", "db/dac/structwis_1_1DescriptorBindingDesc.html", "db/dac/structwis_1_1DescriptorBindingDesc" ],
      [ "DescriptorTable", "d4/def/structwis_1_1DescriptorTable.html", "d4/def/structwis_1_1DescriptorTable" ],
      [ "DescriptorTableEntry", "da/deb/structwis_1_1DescriptorTableEntry.html", "da/deb/structwis_1_1DescriptorTableEntry" ],
      [ "DeviceConstants", "d9/d87/structwis_1_1DeviceConstants.html", "d9/d87/structwis_1_1DeviceConstants" ],
      [ "DeviceExtQuery", "dd/d32/structwis_1_1DeviceExtQuery.html", "dd/d32/structwis_1_1DeviceExtQuery" ],
      [ "FactoryExtQuery", "d4/d04/structwis_1_1FactoryExtQuery.html", "d4/d04/structwis_1_1FactoryExtQuery" ],
      [ "HitGroupDesc", "d4/d9c/structwis_1_1HitGroupDesc.html", "d4/d9c/structwis_1_1HitGroupDesc" ],
      [ "InputAttribute", "d9/d99/structwis_1_1InputAttribute.html", "d9/d99/structwis_1_1InputAttribute" ],
      [ "InputLayout", "d6/d58/structwis_1_1InputLayout.html", "d6/d58/structwis_1_1InputLayout" ],
      [ "InputSlotDesc", "d3/d8b/structwis_1_1InputSlotDesc.html", "d3/d8b/structwis_1_1InputSlotDesc" ],
      [ "is_flag_enum", "d3/dd0/structwis_1_1is__flag__enum.html", null ],
      [ "is_flag_enum< wis::AccelerationStructureFlags >", "d3/d5f/structwis_1_1is__flag__enum_3_01wis_1_1AccelerationStructureFlags_01_4.html", null ],
      [ "is_flag_enum< wis::AdapterFlags >", "db/d08/structwis_1_1is__flag__enum_3_01wis_1_1AdapterFlags_01_4.html", null ],
      [ "is_flag_enum< wis::ASGeometryFlags >", "d2/d7f/structwis_1_1is__flag__enum_3_01wis_1_1ASGeometryFlags_01_4.html", null ],
      [ "is_flag_enum< wis::ASInstanceFlags >", "d6/df1/structwis_1_1is__flag__enum_3_01wis_1_1ASInstanceFlags_01_4.html", null ],
      [ "is_flag_enum< wis::BarrierSync >", "d1/d66/structwis_1_1is__flag__enum_3_01wis_1_1BarrierSync_01_4.html", null ],
      [ "is_flag_enum< wis::BufferUsage >", "df/d99/structwis_1_1is__flag__enum_3_01wis_1_1BufferUsage_01_4.html", null ],
      [ "is_flag_enum< wis::ColorComponents >", "d9/deb/structwis_1_1is__flag__enum_3_01wis_1_1ColorComponents_01_4.html", null ],
      [ "is_flag_enum< wis::DSSelect >", "de/d59/structwis_1_1is__flag__enum_3_01wis_1_1DSSelect_01_4.html", null ],
      [ "is_flag_enum< wis::FenceFlags >", "d0/df8/structwis_1_1is__flag__enum_3_01wis_1_1FenceFlags_01_4.html", null ],
      [ "is_flag_enum< wis::MemoryFlags >", "d1/d1f/structwis_1_1is__flag__enum_3_01wis_1_1MemoryFlags_01_4.html", null ],
      [ "is_flag_enum< wis::PipelineFlags >", "d4/d91/structwis_1_1is__flag__enum_3_01wis_1_1PipelineFlags_01_4.html", null ],
      [ "is_flag_enum< wis::RenderPassFlags >", "d7/dc3/structwis_1_1is__flag__enum_3_01wis_1_1RenderPassFlags_01_4.html", null ],
      [ "is_flag_enum< wis::ResourceAccess >", "d9/d3f/structwis_1_1is__flag__enum_3_01wis_1_1ResourceAccess_01_4.html", null ],
      [ "is_flag_enum< wis::TextureUsage >", "d8/d6c/structwis_1_1is__flag__enum_3_01wis_1_1TextureUsage_01_4.html", null ],
      [ "PushConstant", "df/d6e/structwis_1_1PushConstant.html", "df/d6e/structwis_1_1PushConstant" ],
      [ "PushDescriptor", "d9/d7c/structwis_1_1PushDescriptor.html", "d9/d7c/structwis_1_1PushDescriptor" ],
      [ "RasterizerDesc", "de/d30/structwis_1_1RasterizerDesc.html", "de/d30/structwis_1_1RasterizerDesc" ],
      [ "RaytracingConstants", "da/d42/structwis_1_1RaytracingConstants.html", "da/d42/structwis_1_1RaytracingConstants" ],
      [ "RaytracingDispatchDesc", "de/d0e/structwis_1_1RaytracingDispatchDesc.html", "de/d0e/structwis_1_1RaytracingDispatchDesc" ],
      [ "RenderAttachmentsDesc", "de/df1/structwis_1_1RenderAttachmentsDesc.html", "de/df1/structwis_1_1RenderAttachmentsDesc" ],
      [ "RenderTargetDesc", "dc/da8/structwis_1_1RenderTargetDesc.html", "dc/da8/structwis_1_1RenderTargetDesc" ],
      [ "Result", "d5/dc8/structwis_1_1Result.html", "d5/dc8/structwis_1_1Result" ],
      [ "ResultValue", "d2/dcd/structwis_1_1ResultValue.html", null ],
      [ "SampleDesc", "d4/d8c/structwis_1_1SampleDesc.html", "d4/d8c/structwis_1_1SampleDesc" ],
      [ "SamplerDesc", "d4/d59/structwis_1_1SamplerDesc.html", "d4/d59/structwis_1_1SamplerDesc" ],
      [ "Scissor", "d0/d3a/structwis_1_1Scissor.html", "d0/d3a/structwis_1_1Scissor" ],
      [ "ShaderBindingTableInfo", "dd/d11/structwis_1_1ShaderBindingTableInfo.html", "dd/d11/structwis_1_1ShaderBindingTableInfo" ],
      [ "ShaderExport", "d1/d74/structwis_1_1ShaderExport.html", "d1/d74/structwis_1_1ShaderExport" ],
      [ "ShaderResourceDesc", "d5/d65/structwis_1_1ShaderResourceDesc.html", "d5/d65/structwis_1_1ShaderResourceDesc" ],
      [ "Size2D", "d9/d51/structwis_1_1Size2D.html", null ],
      [ "Size3D", "d1/dcc/structwis_1_1Size3D.html", "d1/dcc/structwis_1_1Size3D" ],
      [ "StencilDesc", "df/dea/structwis_1_1StencilDesc.html", "df/dea/structwis_1_1StencilDesc" ],
      [ "SubresourceRange", "db/de0/structwis_1_1SubresourceRange.html", "db/de0/structwis_1_1SubresourceRange" ],
      [ "SwapchainDesc", "d6/d4f/structwis_1_1SwapchainDesc.html", "d6/d4f/structwis_1_1SwapchainDesc" ],
      [ "TextureBarrier", "df/da5/structwis_1_1TextureBarrier.html", "df/da5/structwis_1_1TextureBarrier" ],
      [ "TextureCopyRegion", "de/d1c/structwis_1_1TextureCopyRegion.html", "de/d1c/structwis_1_1TextureCopyRegion" ],
      [ "TextureDesc", "d1/d9c/structwis_1_1TextureDesc.html", "d1/d9c/structwis_1_1TextureDesc" ],
      [ "TextureRegion", "d7/dbd/structwis_1_1TextureRegion.html", "d7/dbd/structwis_1_1TextureRegion" ],
      [ "TopLevelASBuildDesc", "de/dfd/structwis_1_1TopLevelASBuildDesc.html", "de/dfd/structwis_1_1TopLevelASBuildDesc" ],
      [ "UnorderedAccessDesc", "d4/da5/structwis_1_1UnorderedAccessDesc.html", "d4/da5/structwis_1_1UnorderedAccessDesc" ],
      [ "Viewport", "d0/d28/structwis_1_1Viewport.html", "d0/d28/structwis_1_1Viewport" ]
    ] ]
];