var hierarchy =
[
    [ "wis::AcceleratedGeometryInput", "d7/d87/structwis_1_1AcceleratedGeometryInput.html", null ],
    [ "wis::AdapterDesc", "d3/d9f/structwis_1_1AdapterDesc.html", null ],
    [ "wis::AllocationInfo", "dc/dce/structwis_1_1AllocationInfo.html", null ],
    [ "wis::ASAllocationInfo", "de/d1e/structwis_1_1ASAllocationInfo.html", null ],
    [ "wis::BlendAttachmentDesc", "d0/d08/structwis_1_1BlendAttachmentDesc.html", null ],
    [ "wis::BlendStateDesc", "dd/d2e/structwis_1_1BlendStateDesc.html", null ],
    [ "wis::BufferBarrier", "d1/dca/structwis_1_1BufferBarrier.html", null ],
    [ "wis::BufferRegion", "da/d8d/structwis_1_1BufferRegion.html", null ],
    [ "wis::BufferTextureCopyRegion", "dc/d8d/structwis_1_1BufferTextureCopyRegion.html", null ],
    [ "wis::ComponentMapping", "da/d32/structwis_1_1ComponentMapping.html", null ],
    [ "wis::DepthStencilDesc", "d2/d0b/structwis_1_1DepthStencilDesc.html", null ],
    [ "wis::DescriptorBindingDesc", "db/dac/structwis_1_1DescriptorBindingDesc.html", null ],
    [ "wis::DescriptorTable", "d4/def/structwis_1_1DescriptorTable.html", null ],
    [ "wis::DescriptorTableEntry", "da/deb/structwis_1_1DescriptorTableEntry.html", null ],
    [ "wis::DeviceConstants", "d9/d87/structwis_1_1DeviceConstants.html", null ],
    [ "wis::DeviceExtQuery", "dd/d32/structwis_1_1DeviceExtQuery.html", null ],
    [ "wis::FactoryExtQuery", "d4/d04/structwis_1_1FactoryExtQuery.html", null ],
    [ "std::false_type", null, [
      [ "wis::is_flag_enum< T >", "d3/dd0/structwis_1_1is__flag__enum.html", null ]
    ] ],
    [ "wis::HitGroupDesc", "d4/d9c/structwis_1_1HitGroupDesc.html", null ],
    [ "wis::InputAttribute", "d9/d99/structwis_1_1InputAttribute.html", null ],
    [ "wis::InputLayout", "d6/d58/structwis_1_1InputLayout.html", null ],
    [ "wis::InputSlotDesc", "d3/d8b/structwis_1_1InputSlotDesc.html", null ],
    [ "wis::PushConstant", "df/d6e/structwis_1_1PushConstant.html", null ],
    [ "wis::PushDescriptor", "d9/d7c/structwis_1_1PushDescriptor.html", null ],
    [ "wis::RasterizerDesc", "de/d30/structwis_1_1RasterizerDesc.html", null ],
    [ "wis::RaytracingConstants", "da/d42/structwis_1_1RaytracingConstants.html", null ],
    [ "wis::RaytracingDispatchDesc", "de/d0e/structwis_1_1RaytracingDispatchDesc.html", null ],
    [ "wis::RenderAttachmentsDesc", "de/df1/structwis_1_1RenderAttachmentsDesc.html", null ],
    [ "wis::RenderTargetDesc", "dc/da8/structwis_1_1RenderTargetDesc.html", null ],
    [ "wis::Result", "d5/dc8/structwis_1_1Result.html", null ],
    [ "wis::ResultValue< RetTy >", "d2/dcd/structwis_1_1ResultValue.html", null ],
    [ "wis::SampleDesc", "d4/d8c/structwis_1_1SampleDesc.html", null ],
    [ "wis::SamplerDesc", "d4/d59/structwis_1_1SamplerDesc.html", null ],
    [ "wis::Scissor", "d0/d3a/structwis_1_1Scissor.html", null ],
    [ "wis::ShaderBindingTableInfo", "dd/d11/structwis_1_1ShaderBindingTableInfo.html", null ],
    [ "wis::ShaderExport", "d1/d74/structwis_1_1ShaderExport.html", null ],
    [ "wis::ShaderResourceDesc", "d5/d65/structwis_1_1ShaderResourceDesc.html", null ],
    [ "wis::Size2D", "d9/d51/structwis_1_1Size2D.html", null ],
    [ "wis::Size3D", "d1/dcc/structwis_1_1Size3D.html", null ],
    [ "wis::StencilDesc", "df/dea/structwis_1_1StencilDesc.html", null ],
    [ "wis::SubresourceRange", "db/de0/structwis_1_1SubresourceRange.html", null ],
    [ "wis::SwapchainDesc", "d6/d4f/structwis_1_1SwapchainDesc.html", null ],
    [ "wis::TextureBarrier", "df/da5/structwis_1_1TextureBarrier.html", null ],
    [ "wis::TextureCopyRegion", "de/d1c/structwis_1_1TextureCopyRegion.html", null ],
    [ "wis::TextureDesc", "d1/d9c/structwis_1_1TextureDesc.html", null ],
    [ "wis::TextureRegion", "d7/dbd/structwis_1_1TextureRegion.html", null ],
    [ "wis::TopLevelASBuildDesc", "de/dfd/structwis_1_1TopLevelASBuildDesc.html", null ],
    [ "std::true_type", null, [
      [ "wis::is_flag_enum< wis::ASGeometryFlags >", "d2/d7f/structwis_1_1is__flag__enum_3_01wis_1_1ASGeometryFlags_01_4.html", null ],
      [ "wis::is_flag_enum< wis::ASInstanceFlags >", "d6/df1/structwis_1_1is__flag__enum_3_01wis_1_1ASInstanceFlags_01_4.html", null ],
      [ "wis::is_flag_enum< wis::AccelerationStructureFlags >", "d3/d5f/structwis_1_1is__flag__enum_3_01wis_1_1AccelerationStructureFlags_01_4.html", null ],
      [ "wis::is_flag_enum< wis::AdapterFlags >", "db/d08/structwis_1_1is__flag__enum_3_01wis_1_1AdapterFlags_01_4.html", null ],
      [ "wis::is_flag_enum< wis::BarrierSync >", "d1/d66/structwis_1_1is__flag__enum_3_01wis_1_1BarrierSync_01_4.html", null ],
      [ "wis::is_flag_enum< wis::BufferUsage >", "df/d99/structwis_1_1is__flag__enum_3_01wis_1_1BufferUsage_01_4.html", null ],
      [ "wis::is_flag_enum< wis::ColorComponents >", "d9/deb/structwis_1_1is__flag__enum_3_01wis_1_1ColorComponents_01_4.html", null ],
      [ "wis::is_flag_enum< wis::DSSelect >", "de/d59/structwis_1_1is__flag__enum_3_01wis_1_1DSSelect_01_4.html", null ],
      [ "wis::is_flag_enum< wis::FenceFlags >", "d0/df8/structwis_1_1is__flag__enum_3_01wis_1_1FenceFlags_01_4.html", null ],
      [ "wis::is_flag_enum< wis::MemoryFlags >", "d1/d1f/structwis_1_1is__flag__enum_3_01wis_1_1MemoryFlags_01_4.html", null ],
      [ "wis::is_flag_enum< wis::PipelineFlags >", "d4/d91/structwis_1_1is__flag__enum_3_01wis_1_1PipelineFlags_01_4.html", null ],
      [ "wis::is_flag_enum< wis::RenderPassFlags >", "d7/dc3/structwis_1_1is__flag__enum_3_01wis_1_1RenderPassFlags_01_4.html", null ],
      [ "wis::is_flag_enum< wis::ResourceAccess >", "d9/d3f/structwis_1_1is__flag__enum_3_01wis_1_1ResourceAccess_01_4.html", null ],
      [ "wis::is_flag_enum< wis::TextureUsage >", "d8/d6c/structwis_1_1is__flag__enum_3_01wis_1_1TextureUsage_01_4.html", null ]
    ] ],
    [ "wis::UnorderedAccessDesc", "d4/da5/structwis_1_1UnorderedAccessDesc.html", null ],
    [ "wis::Viewport", "d0/d28/structwis_1_1Viewport.html", null ]
];