// Generated by wisdom generator on 2023-11-01 15:12:02.7079725 GMT+1
#pragma once
#include <stdint.h>
#include <stdbool.h>

typedef struct WisResult WisResult;
typedef struct WisAdapterDesc WisAdapterDesc;
typedef struct WisRootConstant WisRootConstant;
typedef struct WisPushDescriptor WisPushDescriptor;
typedef enum WisShaderStages WisShaderStages;
typedef enum WisStatus WisStatus;
typedef enum WisQueuePriority WisQueuePriority;
typedef enum WisDescriptorType WisDescriptorType;
typedef enum WisQueueType WisQueueType;
typedef enum WisMutiWaitFlags WisMutiWaitFlags;
typedef enum WisAdapterPreference WisAdapterPreference;
typedef enum WisSeverity WisSeverity;
typedef enum WisAdapterFlagsBits WisAdapterFlagsBits;
typedef uint32_t WisAdapterFlags;
typedef enum WisDeviceFeaturesBits WisDeviceFeaturesBits;
typedef uint32_t WisDeviceFeatures;
typedef struct DX12GraphicsPipelineDesc DX12GraphicsPipelineDesc;
typedef struct VKGraphicsPipelineDesc VKGraphicsPipelineDesc;
typedef struct DX12FenceView DX12FenceView;
typedef struct VKFenceView VKFenceView;
typedef struct DX12ShaderView DX12ShaderView;
typedef struct VKShaderView VKShaderView;
typedef struct DX12RootSignatureView DX12RootSignatureView;
typedef struct VKRootSignatureView VKRootSignatureView;
typedef struct DX12GraphicsShaderStages DX12GraphicsShaderStages;
typedef struct VKGraphicsShaderStages VKGraphicsShaderStages;

enum WisShaderStages {
    ShaderStagesAll = 0,
    ShaderStagesVertex = 1,
    ShaderStagesHull = 2,
    ShaderStagesDomain = 3,
    ShaderStagesGeometry = 4,
    ShaderStagesPixel = 5,
    ShaderStagesAmplification = 6,
    ShaderStagesMesh = 7,
};

enum WisStatus {
    StatusOk = 0,
    StatusTimeout = 1,
    StatusError = -1,
    StatusInvalidArgument = -2,
    StatusOutOfMemory = -3,
    StatusDeviceLost = -4,
};

enum WisQueuePriority {
    QueuePriorityCommon = 0,
    QueuePriorityHigh = 100,
    QueuePriorityRealtime = 10000,
};

enum WisDescriptorType {
    DescriptorTypeNone = 0,
    DescriptorTypeConstantBuffer = 2,
    DescriptorTypeShaderResource = 3,
    DescriptorTypeUnorderedAccess = 4,
};

enum WisQueueType {
    QueueTypeGraphics = 0,
    QueueTypeDX12Bundle = 1,
    QueueTypeCompute = 2,
    QueueTypeCopy = 3,
    QueueTypeVideoDecode = 4,
    QueueTypeDX12VideoProcess = 5,
    QueueTypeDX12VideoEncode = 6,
};

enum WisMutiWaitFlags {
    MutiWaitFlagsAll = 0,
    MutiWaitFlagsAny = 1,
};

enum WisAdapterPreference {
    AdapterPreferenceNone = 0,
    AdapterPreferenceMinConsumption = 1,
    AdapterPreferencePerformance = 2,
};

enum WisSeverity {
    SeverityDebug = 0,
    SeverityTrace = 1,
    SeverityInfo = 2,
    SeverityWarning = 3,
    SeverityError = 4,
    SeverityCritical = 5,
};

enum WisAdapterFlagsBits {
    AdapterFlagsNone = 0x0,
    AdapterFlagsRemote = 1 << 0,
    AdapterFlagsSoftware = 1 << 1,
    AdapterFlagsDX12ACGCompatible = 1 << 2,
    AdapterFlagsDX12SupportsMonitoredFences = 1 << 3,
    AdapterFlagsDX12SupportsNonMonitoredFences = 1 << 4,
    AdapterFlagsDX12KeyedMutexConformance = 1 << 5,
};

enum WisDeviceFeaturesBits {
    DeviceFeaturesNone = 0x0,
    DeviceFeaturesPushDescriptors = 1 << 0,
};

struct WisResult{
    WisStatus status;
    const char* error;
};

struct WisAdapterDesc{
    const char description[256];
    uint32_t vendor_id;
    uint32_t device_id;
    uint32_t subsys_id;
    uint32_t revision;
    uint64_t dedicated_video_memory;
    uint64_t dedicated_system_memory;
    uint64_t shared_system_memory;
    uint64_t adapter_id;
    WisAdapterFlags flags;
};

struct WisRootConstant{
    WisShaderStages stage;
    uint32_t size_bytes;
};

struct WisPushDescriptor{
    WisShaderStages stage;
    uint32_t bind_register;
    WisDescriptorType type;
    uint32_t reserved;
};

struct DX12GraphicsPipelineDesc{
    DX12RootSignatureView root_signature;
    DX12GraphicsShaderStages shaders;
};

struct VKGraphicsPipelineDesc{
    VKRootSignatureView root_signature;
    VKGraphicsShaderStages shaders;
};

struct DX12FenceView{
    void* value;
};

struct VKFenceView{
    void* value;
};

struct DX12ShaderView{
    void* bytecode;
    uint32_t size_bytes;
};

struct VKShaderView{
    void* value;
};

struct DX12RootSignatureView{
    void* value;
};

struct VKRootSignatureView{
    void* value;
};

struct DX12GraphicsShaderStages{
    DX12ShaderView vertex;
    DX12ShaderView hull;
    DX12ShaderView domain;
    DX12ShaderView geometry;
    DX12ShaderView pixel;
};

struct VKGraphicsShaderStages{
    VKShaderView vertex;
    VKShaderView hull;
    VKShaderView domain;
    VKShaderView geometry;
    VKShaderView pixel;
};

//=================================DELEGATES=================================

typedef void (*DebugCallback)( WisSeverity severity,  const char* message,  void* user_data);
//==================================HANDLES==================================

typedef struct DX12CommandQueue_t* DX12CommandQueue;
typedef struct VKCommandQueue_t* VKCommandQueue;

typedef struct DX12RootSignature_t* DX12RootSignature;
typedef struct VKRootSignature_t* VKRootSignature;

typedef struct DX12Factory_t* DX12Factory;
typedef struct VKFactory_t* VKFactory;

typedef struct DX12PipelineState_t* DX12PipelineState;
typedef struct VKPipelineState_t* VKPipelineState;

typedef struct DX12Adapter_t* DX12Adapter;
typedef struct VKAdapter_t* VKAdapter;

typedef struct DX12Device_t* DX12Device;
typedef struct VKDevice_t* VKDevice;

typedef struct DX12Fence_t* DX12Fence;
typedef struct VKFence_t* VKFence;

typedef struct DX12ResourceAllocator_t* DX12ResourceAllocator;
typedef struct VKResourceAllocator_t* VKResourceAllocator;

typedef struct DX12Shader_t* DX12Shader;
typedef struct VKShader_t* VKShader;

//=================================FUNCTIONS=================================

WisResult DX12CreateFactory( bool debug_layer,  DebugCallback callback,  void* user_data, DX12Factory* out_factory);
WisResult VKCreateFactory( bool debug_layer,  DebugCallback callback,  void* user_data, VKFactory* out_factory);
WisResult DX12CreateDevice( DX12Factory factory,  DX12Adapter adapter, DX12Device* out_device);
WisResult VKCreateDevice( VKFactory factory,  VKAdapter adapter, VKDevice* out_device);
WisResult DX12GetAdapter(DX12Factory self,  uint32_t index,  WisAdapterPreference preference, DX12Adapter* out_adapter);
WisResult VKGetAdapter(VKFactory self,  uint32_t index,  WisAdapterPreference preference, VKAdapter* out_adapter);
void DX12FactoryDestroy(DX12Factory self);
void VKFactoryDestroy(VKFactory self);
WisResult DX12GetDesc(DX12Adapter self,  WisAdapterDesc* desc);
WisResult VKGetDesc(VKAdapter self,  WisAdapterDesc* desc);
void DX12DeviceDestroy(DX12Device self);
void VKDeviceDestroy(VKDevice self);
WisResult DX12CreateFence(DX12Device self,  uint64_t initial_value, DX12Fence* out_fence);
WisResult VKCreateFence(VKDevice self,  uint64_t initial_value, VKFence* out_fence);
WisResult DX12CreateRootSignature(DX12Device self,  WisRootConstant* constants,  uint32_t constants_size, DX12RootSignature* out_root_signature);
WisResult VKCreateRootSignature(VKDevice self,  WisRootConstant* constants,  uint32_t constants_size, VKRootSignature* out_root_signature);
WisResult DX12CreateAllocator(DX12Device self, DX12ResourceAllocator* out_allocator);
WisResult VKCreateAllocator(VKDevice self, VKResourceAllocator* out_allocator);
WisResult DX12CreateCommandQueue(DX12Device self,  WisQueueType type,  WisQueuePriority priority, DX12CommandQueue* out_queue);
WisResult VKCreateCommandQueue(VKDevice self,  WisQueueType type,  WisQueuePriority priority, VKCommandQueue* out_queue);
WisResult DX12CreateShader(DX12Device self,  void* data,  uint32_t size_bytes, DX12Shader* out_shader);
WisResult VKCreateShader(VKDevice self,  void* data,  uint32_t size_bytes, VKShader* out_shader);
WisResult DX12WaitForMultipleFences(DX12Device self,  DX12FenceView* fences,  uint64_t* values,  uint32_t count,  WisMutiWaitFlags wait_all,  uint64_t timeout);
WisResult VKWaitForMultipleFences(VKDevice self,  VKFenceView* fences,  uint64_t* values,  uint32_t count,  WisMutiWaitFlags wait_all,  uint64_t timeout);
void DX12RootSignatureDestroy(DX12RootSignature self);
void VKRootSignatureDestroy(VKRootSignature self);
void DX12FenceDestroy(DX12Fence self);
void VKFenceDestroy(VKFence self);
uint64_t DX12GetCompletedValue(DX12Fence self);
uint64_t VKGetCompletedValue(VKFence self);
WisResult DX12Wait(DX12Fence self,  uint64_t value,  uint64_t timeout_ns);
WisResult VKWait(VKFence self,  uint64_t value,  uint64_t timeout_ns);
WisResult DX12Signal(DX12Fence self,  uint64_t value);
WisResult VKSignal(VKFence self,  uint64_t value);
void DX12ResourceAllocatorDestroy(DX12ResourceAllocator self);
void VKResourceAllocatorDestroy(VKResourceAllocator self);
void DX12CommandQueueDestroy(DX12CommandQueue self);
void VKCommandQueueDestroy(VKCommandQueue self);
void DX12ShaderDestroy(DX12Shader self);
void VKShaderDestroy(VKShader self);
void DX12PipelineStateDestroy(DX12PipelineState self);
void VKPipelineStateDestroy(VKPipelineState self);
DX12FenceView AsDX12FenceView(DX12Fence self);
VKFenceView AsVKFenceView(VKFence self);
DX12ShaderView AsDX12ShaderView(DX12Shader self);
VKShaderView AsVKShaderView(VKShader self);
DX12RootSignatureView AsDX12RootSignatureView(DX12RootSignature self);
VKRootSignatureView AsVKRootSignatureView(VKRootSignature self);
