/**
 * @page contributing_page Contributing
 *
 * This page provides a comprehensive guide on how to contribute to the Wisdom project.
 *
 * @section overview_sec Overview
 *
 * We welcome contributions to the Wisdom project! Whether you're fixing bugs, adding features, improving documentation,
 * or helping with testing, your contributions are valuable to the community.
 *
 * Most of the time you can just submit an extension. There is a special implemntation pattern there, that is highly
 * permissive. If the extension is implemented correctly for both backends, it will be included in the main repo and
 * reworked to fit the main codebase. You can also submit a PR with a direct change to the main codebase, but it
 * requires a bit more work, because of the need to follow the coding standards and design principles outlined in this
 * document.
 *
 * Before contributing, please familiarize yourself with our codebase structure and coding standards outlined below.
 *
 * @section getting_started_contributing Getting Started
 *
 * 1. **Fork the repository** on GitHub: https://github.com/Agrael1/Wisdom
 * 2. **Clone your fork** locally: `git clone https://github.com/your-username/Wisdom.git`
 * 3. **Create a feature branch**: `git checkout -b feature/your-feature-name`
 * 4. **Set up the build environment** following the @ref getting_started_page "Getting Started" guide
 * 5. **Make your changes** following our coding standards
 * 6. **Test your changes** thoroughly
 * 7. **Submit a pull request**
 *
 * @section coding_standards_sec Coding Standards and Best Practices
 *
 * @subsection code_style Code Style
 *
 * The Wisdom project uses a **custom clang-format configuration** located in `.clang-format` at the root of the
 * repository.
 *
 * **To format your code:**
 * ```bash
 * clang-format -i --style=file your-file.cpp
 * ```
 * Or use your IDE's built-in clang-format support.
 *
 * @note The generator automatically formats generated files using clang-format during the build process.
 * The repo formatting is also enforced in CI using GitHub Actions, so you don't have to worry about it.
 *
 * @subsection naming_conventions Naming Conventions
 *
 * Names follow Windows API conventions where applicable:
 * - **Implementation Classes**: PascalCase (e.g., `DX12DeviceImpl`, `CommandQueue`, `DescriptorStorage`)
 * - **Variables and constants**: snake_case (e.g., `command_list`, `descriptor_heap`)
 * - **Defines**: SCREAMING_SNAKE_CASE (e.g., `WISDOM_VERSION`)
 * - Everything else: should be generated by generator.
 *
 * Implementation classes (e.g., `DX12DeviceImpl`) are internal and @wis_must be in *_types.hpp files under `wis::impl`
 * namespace. They are consumed by the implementation classes, that are generated. You will get a lot of screams from
 * compiler if something is wrong, so don't worry about it. Just follow the pattern and you will be fine. ;)
 *
 * @note I just prefer this style, it is not strictly enforced.
 *
 * @subsection api_design API Design Principles
 *
 * - **Result-based returns**: Most functions return `wis::Result`, otherwise they return the expected type directly. No
 * exceptions or error codes.
 * - **Manual lifetime management**: All resources manage their own lifetime explicitly. Please always think about
 * strict aliasing. There are functions provided, like `wis::from_handle`, to help with this. Don't try to be smart and
 * ignore them, it will only cause problems. The resources @wis_must be initialized with placement new and destroyed
 * with the corresponding destroy function. No smart pointers or RAII wrappers in the main codebase, but feel free to
 * use them in extensions.
 * - **No virtual functions**: Direct API calls for maximum performance, unless designing extension classes for device
 * or instance.
 * - **Platform abstraction**: Code should work on both DirectX 12 and Vulkan backends, unless extensions are explicitly
 * backend-specific.
 *
 * @subsection language_standards Language Standards
 *
 * - **Primary**: C++20 (required).
 * - **Supported**: C++23 features where available. If you want to use C++23 features, please ensure they are supported
 * by all target compilers by using feature macros. Don't use `__cplusplus`! It is unreliable on MSVC.
 *
 * @section build_requirements_sec Build Requirements
 *
 * @subsection cmake_requirements CMake Requirements
 *
 * - **Minimum CMake version**: 3.22
 * - **Build system**: Ninja (recommended)
 * - **Presets**: Use CMake presets for consistent builds, there are a lot of them, so check `CMakePresets.json` for
 * details. You can also create your own presets if needed.
 *
 * @subsection compiler_requirements Compiler Requirements
 *
 * - **Windows**: MSVC 2022 or Clang 16+
 * - **Linux**: GCC 13+ or Clang 16+
 * - **C++20 standard library**: Required for `std::format` (or use `WISDOM_USE_FMT=ON`)
 *
 * @section testing_sec Testing
 *
 * @subsection test_framework Test Framework
 *
 * The project uses **Catch2 v3 Unit Test Framework** for testing. Tests are located in the `tests/` directory.
 * Although graphics API is notoriously difficult to test, if possible, please write tests for any new features or bug
 * fixes you implement. Tests should cover both DirectX 12 and Vulkan backends when applicable.
 *
 * @subsection running_tests Running Tests
 *
 * Tests have presets as well, so you can run them with CMake. For example, to run all tests in debug mode:
 *
 * ```bash
 * # Build the solution
 * cmake . --preset linux-gcc-debug
 * cmake --build --preset linux-gcc-debug
 *
 * # Run tests
 * ctest --preset linux-gcc-debug
 * ```
 *
 *
 * @subsection writing_tests Writing Tests
 *
 * - Place test files in `tests/basic/` or appropriate subdirectory
 * - Use Catch2 macros: `TEST_CASE`, `REQUIRE`, `CHECK`
 * - Test both DirectX 12 and Vulkan backends when applicable
 * - Include proper cleanup and resource management
 *
 * **Example test structure:**
 * ```cpp
 * #include <catch2/catch_test_macros.hpp>
 * #include <wisdom/wisdom.hpp>
 *
 * TEST_CASE("your_test_name") {
 *     // Setup
 *     wis::Result result;
 *     auto factory = wis::CreateFactory(..., result);
 *     REQUIRE(result.status == wis::Status::Ok);
 *
 *     // Test logic
 *     // ...
 *
 *     // Assertions
 *     REQUIRE(condition);
 * }
 * ```
 *
 * @section documentation_sec Documentation
 *
 * @subsection doxygen_docs Doxygen Documentation
 *
 * - All public APIs must be documented with Doxygen comments
 * - Follow RFC 2119 guidelines for requirement levels (MUST, SHOULD, MAY)
 * - Use JavaDoc style and keywords appropriately
 * - Documentation is automatically generated and deployed to GitHub Pages
 *
 * @subsection doc_generation Documentation Generation
 *
 * ```bash
 * # Enable documentation build
 * cmake --preset x64-release -DWISDOM_BUILD_DOCS=ON
 * cmake --build --preset x64-release --target doc_doxygen
 * ```
 *
 * @section submission_guidelines_sec Submission Guidelines
 *
 * @subsection pull_requests Pull Requests
 *
 * 1. **Create descriptive commits**: Use clear, concise commit messages
 * 2. **Target the right branch**: Submit PRs against the `master` branch
 * 3. **Include tests**: New features should include appropriate tests
 * 4. **Update documentation**: Update relevant documentation pages
 * 5. **Check CI**: Ensure all GitHub Actions workflows pass
 *
 * @subsection pr_checklist Pull Request Checklist
 *
 * - [ ] Code follows the project's coding standards
 * - [ ] Code is formatted with clang-format (forced in CI)
 * - [ ] All tests pass locally
 * - [ ] New tests added for new functionality (if applicable)
 * - [ ] Documentation updated (if applicable)
 * - [ ] If breaking changes are introduced, they are clearly documented and justified. The PR will be marked with
 * `vNext` tag.
 * - [ ] Vulkan and DirectX 12 backends both work (if applicable)
 *
 * @subsection commit_messages Commit Message Format
 *
 * Use descriptive commit messages that explain what and why:
 *
 * ```
 * feat: add descriptor buffer extension support
 *
 * - Implement descriptor buffer for both DX12 and Vulkan
 * - Add comprehensive tests for descriptor operations
 * - Update documentation with usage examples
 *
 * Fixes #123
 * ```
 * Those can be generated by AI, but make sure to review and edit them for accuracy and clarity.
 *
 * @section ci_cd_sec Continuous Integration
 *
 * @subsection github_actions GitHub Actions
 *
 * The project uses GitHub Actions for CI/CD with the following workflows:
 *
 * - **Linux build**: Ubuntu with Vulkan backend
 * - **Windows DirectX 12**: MSVC with DirectX 12 backend
 * - **Windows Vulkan**: MSVC with Vulkan backend
 * - **Windows Clang**: Clang with Vulkan and C++20 modules
 * - **Documentation**: Auto-generated and deployed to GitHub Pages
 * - **Release**: Automated NuGet and GitHub releases
 *
 * @subsection build_matrix Build Matrix
 *
 * All PRs are automatically tested against:
 * - **Platforms**: Windows, Linux
 * - **Compilers**: MSVC, Clang, GCC
 * - **Graphics APIs**: DirectX 12, Vulkan
 * - **Build types**: Debug, Release
 *
 * @section contribution_types_sec Types of Contributions
 *
 * @subsection bug_fixes Bug Fixes
 *
 * - Report bugs using GitHub Issues
 * - Include minimal reproduction case
 * - Specify platform, compiler, and graphics API
 * - Test fixes on both graphics backends when possible
 *
 * @subsection feature_additions Feature Additions
 *
 * - Discuss major features in GitHub Issues first
 * - Ensure cross-platform compatibility
 * - Follow existing API patterns
 * - Include comprehensive tests and documentation
 *
 * @subsection documentation_improvements Documentation Improvements
 *
 * - Fix typos, clarify explanations
 * - Add usage examples
 * - Improve API documentation
 * - Update getting started guides
 *
 * @subsection platform_support Platform Support
 *
 * You can contribute by adding support for new platforms or improving existing platform integrations. This may involve:
 * - Add support for new platforms
 * - Improve existing platform integrations
 * - Update CMake configuration
 * - Ensure proper CI coverage
 *
 * @section community_sec Community and Communication
 *
 * - **Repository**: https://github.com/Agrael1/Wisdom
 * - **Issues**: Use GitHub Issues for bug reports and feature requests
 * - **Discussions**: Use GitHub Discussions for questions and general discussion
 * - **Contact**: agrael@live.ru (for code of conduct violations)
 *
 * @section license_sec License
 *
 * By contributing to Wisdom, you agree that your contributions will be licensed under the same license as the project.
 * Please see the LICENSE.txt file in the repository root for details.
 *
 * @note Thank you for your interest in contributing to Wisdom! Your contributions help make this library better for
 * everyone.
 */

/**
 * @page agility_page Agility SDK
 * This page is dedicated to providing information about using the Agility SDK with Wisdom for DirectX 12 development on
 * Windows. The Agility SDK allows developers to access the latest DirectX 12 features on older Windows versions, but it
 * requires additional setup and dependencies compared to using the Windows SDK.
 *
 * @section what_happened_sec What Happened to the Agility SDK?
 *
 * If you have used Wisdom before, you may have noticed that the Agility SDK is no longer included as a default option
 * for DirectX 12 development. This change was made to simplify the build process and reduce the number of dependencies.
 * This in turn was done for a few reasons:
 * - The Agility SDK breaks the Conan package, because it is not available as a Conan package and it requires manual
 * installation and setup. This makes it difficult to maintain and use in a consistent way across different
 * environments.
 * - The Agility SDK is not required for most users, as the Windows SDK provides access to the latest DirectX 12
 * features on Windows 11 and Windows 10 (with the latest updates). For users who need to support older Windows
 * versions, the Agility SDK can still be used by enabling the `WISDOM_USE_AGILITY_SDK` CMake option and following the
 * setup instructions below.
 * - The Agility SDK break transparency of the library, because it requires additional setup and exports were hidden
 * behind a CMake command. This makes it difficult to use the library in a consistent way across different environments
 * and platforms.
 *
 * @section using_agility_sec Using the Agility SDK with Wisdom
 *
 * If you need to use the Agility SDK for your DirectX 12 development on Windows, you can enable it by following these
 * steps:
 *
 * - Install the Agility SDK from the official Microsoft website:
 * https://devblogs.microsoft.com/directx/directx12agility/
 * - *OR* If you are using CMake and sources, define `WISDOM_USE_AGILITY_SDK=ON` before including the library. This will
 * enable the use of the Agility SDK in your project and allow you to access the latest DirectX 12 features.
 * - *OR* If you use distributed binaries, Agility SDK is included in the package.
 *
 * On NuGet, the Agility SDK comes under `Microsoft.Direct3D.D3D12` package, so you need to install it in your project
 * to use the Agility SDK with Wisdom.
 *
 * Next, you need to ensure, that you copy the Agility SDK DLLs (`D3D12Core.dll` and `D3DSDKLayers.dll`) to your output
 * directory under `/D3D12/` folder. You can do this manually, or you can add a post-build step in your project settings
 * to copy the DLLs automatically. NuGet package should do this for you, but if you are using CMake and sources, you
 * need to set this up yourself. You can use provided CMake function `wis_install_agility_win32` to copy the DLLs to your
 * output directory.
 * 
 * And finally, you need to export the symbols for the Agility SDK in your code. This is required when linking against
 * the Agility SDK on Windows, as it uses a different set of symbols than the Windows SDK. You can do this by adding the
 * following line to your code:
 * 
 * ```c
 * WISDOM_EXPORT_AGILITY_SYMBOLS();
 * ```
 * 
 * `WISDOM_EXPORT_AGILITY_SYMBOLS` requires defined `DX12SDKVER`. This macro is defined from sources/.zip distribution when
 * `WISDOM_USE_AGILITY_SDK` is enabled, but if you are using custom SDK or NuGet you will need another macro.
 * 
 * `WISDOM_EXPORT_AGILITY_CUSTOM(SDK_VER)` is a helper macro that allows you to use custom SDK version.
 * Otherwise you can directly export symbols in your executable the way Agility SDK documentation describes:
 * https://devblogs.microsoft.com/directx/gettingstarted-dx12agility/
 * 
 * @section agility_conclusion_sec Conclusion
 * Wisdom Library automatically uses the Agility SDK, when it is enabled.
 * .zip distribution includes the Agility SDK, so you don't have to worry about it if you are using that. If you are
 * using CMake and sources, you can enable it with a single CMake option, but you need to set up the DLL copying
 * yourself. On NuGet, you need to install the `Microsoft.Direct3D.D3D12` package and ensure the DLLs are copied to your
 * output directory.
 * 
 * It is not easy to set up, but sometimes it is necessary to support older Windows versions, so we provide the option
 * to use it. If you don't need to, you can just ignore it and use the Windows SDK that comes with your system, which
 * should work fine for most users.
 */
