<?xml version="1.0"?>
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <WisdomVulkanEnabled Condition="Exists('$(WisdomVulkanSDKPath)')">true</WisdomVulkanEnabled>
  </PropertyGroup>
  <ItemDefinitionGroup>
    <ClCompile>
      <AdditionalIncludeDirectories>$(MSBuildThisFileDirectory)..\..\include\;$(MSBuildThisFileDirectory)..\..\include\dxma;$(MSBuildThisFileDirectory)..\..\include\d3dx12;%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>
      <AdditionalIncludeDirectories Condition="'$(WisdomVulkanEnabled)' == 'true'">$(MSBuildThisFileDirectory)..\..\include\vkma;%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>
      <AdditionalIncludeDirectories Condition="Exists('$(WisdomVulkanSDKPath)')">$(WisdomVulkanSDKPath);%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>

      <PreprocessorDefinitions Condition="'$(WisdomVulkanEnabled)' == 'true'">WISDOM_VULKAN=1;%(PreprocessorDefinitions)</PreprocessorDefinitions>
      <PreprocessorDefinitions>WISDOM_DX12=1;WISDOM_WINDOWS=1;%(PreprocessorDefinitions)</PreprocessorDefinitions>

      <PreprocessorDefinitions Condition="'$(WisdomForceVulkan)' == 'true'">WISDOM_FORCE_VULKAN=1;%(PreprocessorDefinitions)</PreprocessorDefinitions>
      <PreprocessorDefinitions Condition="'$(WisdomLinkage)' == 'dynamic'">WISDOM_SHARED_LIBRARY=1;%(PreprocessorDefinitions)</PreprocessorDefinitions>
      <PreprocessorDefinitions Condition="'$(WisdomLinkage)' == 'headers'">WISDOM_HEADER_ONLY=1;%(PreprocessorDefinitions)</PreprocessorDefinitions>
      <PreprocessorDefinitions Condition="'$(WisdomPlatformExtension)' == 'true'">WIS_PLATFORM_WIN32_PRESENT=1;WISDOM_PLATFORM_UWP_PRESENT=1;%(PreprocessorDefinitions)</PreprocessorDefinitions>
      <PreprocessorDefinitions Condition="'$(WisdomPlatformExtension)' == 'true' and '$(WisdomLinkage)' != 'dynamic'">WISDOM_PLATFORM_STATIC=1;%(PreprocessorDefinitions)</PreprocessorDefinitions>
      <PreprocessorDefinitions Condition="'$(WisdomPlatformExtension)' == 'true' and '$(WisdomLinkage)' == 'dynamic'">WISDOM_PLATFORM_SHARED_LIBRARY=1;%(PreprocessorDefinitions)</PreprocessorDefinitions>
    </ClCompile>

    <Link>
      <AdditionalDependencies Condition="'$(WisdomLinkage)' == 'static'">$(MSBuildThisFileDirectory)..\..\lib\wisdom$(LP).lib;%(AdditionalDependencies)</AdditionalDependencies>
      <AdditionalDependencies Condition="'$(WisdomLinkage)' == 'dynamic'">$(MSBuildThisFileDirectory)..\..\lib\wisdom-shared$(LP).lib;%(AdditionalDependencies)</AdditionalDependencies>
      <AdditionalDependencies Condition="'$(WisdomPlatformExtension)' == 'true' and '$(WisdomLinkage)' == 'static'">$(MSBuildThisFileDirectory)..\..\lib\wisdom-platform$(LP).lib;%(AdditionalDependencies)</AdditionalDependencies>
      <AdditionalDependencies Condition="'$(WisdomPlatformExtension)' == 'true' and '$(WisdomLinkage)' == 'dynamic'">$(MSBuildThisFileDirectory)..\..\lib\wisdom-platform-shared$(LP).lib;%(AdditionalDependencies)</AdditionalDependencies>
      <AdditionalDependencies Condition="'$(WisdomVulkanEnabled)' == 'true'"> $(MSBuildThisFileDirectory)..\..\lib\vkma$(LP).lib;%(AdditionalDependencies)</AdditionalDependencies>
      <AdditionalDependencies> $(MSBuildThisFileDirectory)..\..\lib\DX12Allocator$(LP).lib;$(MSBuildThisFileDirectory)..\..\lib\DX12Agility$(LP).lib;dxguid.lib;DXGI.lib;%(AdditionalDependencies)</AdditionalDependencies>
    </Link>

		<!-- Deploy DLLs for dynamic linkage - works for both Win32 and WinRT/UWP -->
		<ItemGroup Condition="'$(WisdomLinkage)' == 'dynamic'">
			<None Include="$(MSBuildThisFileDirectory)..\..\bin\wisdom-shared$(LP).dll">
				<Link>wisdom-shared$(LP).dll</Link>
				<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
				<!-- WinRT/UWP specific: include in app package -->
				<DeploymentContent>true</DeploymentContent>
			</None>
      <None Condition="'$(WisdomPlatformExtension)' == 'true'" Include="$(MSBuildThisFileDirectory)..\..\bin\wisdom-platform-shared$(LP).dll">
        <Link>wisdom-platform-shared$(LP).dll</Link>
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        <!-- WinRT/UWP specific: include in app package -->
        <DeploymentContent>true</DeploymentContent>
      </None>
		</ItemGroup>

  </ItemDefinitionGroup>
</Project>
