// Generated by wisdom generator on 2023-11-02 00:00:59.4572573 GMT+1
#pragma once
#include <wisdom/vulkan/xvk_views.h>

namespace wis{
struct VKGraphicsShaderStages{
    wis::VKShaderView vertex;
    wis::VKShaderView hull;
    wis::VKShaderView domain;
    wis::VKShaderView geometry;
    wis::VKShaderView pixel;
};

struct VKGraphicsPipelineDesc{
    wis::VKRootSignatureView root_signature;
    wis::VKGraphicsShaderStages shaders;
};

}
