<Project>
  <PropertyGroup>
    <WisdomLinkage Condition="'$(WisdomLinkage)' == ''">static</WisdomLinkage>
    <WisdomForceVulkan Condition="'$(WisdomForceVulkan)' == ''">false</WisdomForceVulkan>
    <WisdomVulkanSDKPath Condition="'$(WisdomVulkanSDKPath)' == ''">$(VULKAN_SDK)\Include</WisdomVulkanSDKPath>

    <LibraryPostfix Condition="'$(Configuration)' == 'Debug'">d</LibraryPostfix>
    <LibraryPostfix Condition="'$(Configuration)' != 'Debug'"></LibraryPostfix>
    <LP>$(LibraryPostfix)</LP>
  </PropertyGroup>

  <ItemGroup>
    <PropertyPageSchema Include="$(MSBuildThisFileDirectory)\wisdom.xml"/>
    <ProjectCapability Include="Wisdom" />
  </ItemGroup>
</Project>
